# Generated by Django 4.2.5 on 2023-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yousta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloths',
            name='material',
            field=models.CharField(choices=[('linen', 'linen'), ('cotton', 'cotton'), ('satin', 'satin'), ('nylon', 'nylon'), ('polyster', 'polyster'), ('silk', 'silk')], default='cotton', max_length=200),
        ),
    ]
